#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgee
Version  : 0.20.0
Release  : 2
URL      : https://download.gnome.org/sources/libgee/0.20/libgee-0.20.0.tar.xz
Source0  : https://download.gnome.org/sources/libgee/0.20/libgee-0.20.0.tar.xz
Summary  : The GObject collection library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgee-lib
Requires: libgee-data
BuildRequires : gobject-introspection-dev
BuildRequires : pkgconfig(glib-2.0)

%description
Libgee is a collection library providing GObject-based interfaces and
classes for commonly used data structures.

%package data
Summary: data components for the libgee package.
Group: Data

%description data
data components for the libgee package.


%package dev
Summary: dev components for the libgee package.
Group: Development
Requires: libgee-lib
Requires: libgee-data
Provides: libgee-devel

%description dev
dev components for the libgee package.


%package lib
Summary: lib components for the libgee package.
Group: Libraries
Requires: libgee-data

%description lib
lib components for the libgee package.


%prep
%setup -q -n libgee-0.20.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1491411326
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1491411326
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gee-0.8.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gee-0.8.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gee-0.8/gee.h
/usr/lib64/libgee-0.8.so
/usr/lib64/pkgconfig/gee-0.8.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgee-0.8.so.2
/usr/lib64/libgee-0.8.so.2.6.0
